use_frameworks!

target 'OnlinePT-Message_Example' do
  pod 'OnlinePT-Message', :path => '../'
  pod 'OnlinePT-BaseCore', :path => '../../OnlinePT-BaseCore'
  pod 'OnlinePT-Config', :path => '../../OnlinePT-Config'

end
